name: deploy client docs
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "18"
    - run: yarn install
    - name: Build
      run: yarn doc build core/client
    - name: copy files via ssh
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.CN_HOST }}
        username: ${{ secrets.CN_USERNAME }}
        key: ${{ secrets.CN_KEY }}
        port: ${{ secrets.CN_PORT }}
        source: "packages/core/client/dist/*"
        target: ${{ secrets.CN_TARGET }}/${{ github.ref_name }}
