name: manual_down_deploy_pr
# deploy_host
# deploy_host_username
# deploy_host_password
on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'pr number is '
        required: true

jobs:
  down_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh down deploy
        uses: appleboy/ssh-action@master
        env:
          pr_number: ${{ inputs.pr_number }}
          pr_compose_dir: pr-${{ inputs.pr_number }}
        with:
          host: ${{ secrets.deploy_host }}
          username: ${{ secrets.deploy_host_username }}
          password: ${{ secrets.deploy_host_password }}
          script: |
            cd /home/ecs-user/nocobase/${{ env.pr_compose_dir }}
            sudo docker compose down
            sudo docker rmi registry.cn-hongkong.aliyuncs.com/nocobase/nocobase:pr-${{ env.pr_number }}
